# Generated by Django 4.1.3 on 2022-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djotify', '0003_alter_artist_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
