# Generated by Django 4.1.3 on 2022-11-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djotify', '0005_alter_artist_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='djotify.album'),
        ),
    ]
