# Generated by Django 4.1.3 on 2022-11-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djotify', '0007_alter_album_created_at_alter_album_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
