# Generated by Django 4.1.3 on 2022-11-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djotify', '0008_alter_song_created_at_alter_song_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
