# Generated by Django 4.1.3 on 2022-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djotify', '0010_alter_album_artist_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
