# Generated by Django 4.1.3 on 2022-11-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djotify', '0012_alter_artist_created_at_alter_artist_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year_released',
            field=models.DateField(blank=True),
        ),
    ]
